//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctTypeIDType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AcctTypeIDType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max11AN">
 *     &lt;enumeration value="Unspecified"/>
 *     &lt;enumeration value="Checking"/>
 *     &lt;enumeration value="Credit"/>
 *     &lt;enumeration value="Deferred"/>
 *     &lt;enumeration value="Charge"/>
 *     &lt;enumeration value="Prepaid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AcctTypeIDType")
@XmlEnum
public enum AcctTypeIDType {

    @XmlEnumValue("Unspecified")
    UNSPECIFIED("Unspecified"),
    @XmlEnumValue("Checking")
    CHECKING("Checking"),
    @XmlEnumValue("Credit")
    CREDIT("Credit"),
    @XmlEnumValue("Deferred")
    DEFERRED("Deferred"),
    @XmlEnumValue("Charge")
    CHARGE("Charge"),
    @XmlEnumValue("Prepaid")
    PREPAID("Prepaid");
    private final String value;

    AcctTypeIDType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AcctTypeIDType fromValue(String v) {
        for (AcctTypeIDType c: AcctTypeIDType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
