//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctFundingSrcType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AcctFundingSrcType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max7AN">
 *     &lt;enumeration value="Debit"/>
 *     &lt;enumeration value="Credit"/>
 *     &lt;enumeration value="Prepaid"/>
 *     &lt;enumeration value="Charge"/>
 *     &lt;enumeration value="DfDebit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AcctFundingSrcType")
@XmlEnum
public enum AcctFundingSrcType {

    @XmlEnumValue("Debit")
    DEBIT("Debit"),
    @XmlEnumValue("Credit")
    CREDIT("Credit"),
    @XmlEnumValue("Prepaid")
    PREPAID("Prepaid"),
    @XmlEnumValue("Charge")
    CHARGE("Charge"),
    @XmlEnumValue("DfDebit")
    DF_DEBIT("DfDebit");
    private final String value;

    AcctFundingSrcType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AcctFundingSrcType fromValue(String v) {
        for (AcctFundingSrcType c: AcctFundingSrcType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
