//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AltMerchNameAndAddrGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AltMerchNameAndAddrGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchName" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchAddr" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchCity" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchState" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchCnty" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchCtry" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchEmail" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchSvcLocCity" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchSvcLocState" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchSvcLocPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchSvcLocCtry" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchSvcLocAddr" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchPhNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchAddConInfo" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchPartnerIDCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AltMerchNameAndAddrGrp", propOrder = {
    "merchName",
    "merchAddr",
    "merchCity",
    "merchState",
    "merchCnty",
    "merchPostalCode",
    "merchCtry",
    "merchEmail",
    "merchSvcLocCity",
    "merchSvcLocState",
    "merchSvcLocPostalCode",
    "merchSvcLocCtry",
    "merchSvcLocAddr",
    "merchPhNum",
    "merchAddConInfo",
    "merchPartnerIDCode"
})
public class AltMerchNameAndAddrGrp {

    @XmlElement(name = "MerchName")
    protected String merchName;
    @XmlElement(name = "MerchAddr")
    protected String merchAddr;
    @XmlElement(name = "MerchCity")
    protected String merchCity;
    @XmlElement(name = "MerchState")
    protected String merchState;
    @XmlElement(name = "MerchCnty")
    protected String merchCnty;
    @XmlElement(name = "MerchPostalCode")
    protected String merchPostalCode;
    @XmlElement(name = "MerchCtry")
    protected String merchCtry;
    @XmlElement(name = "MerchEmail")
    protected String merchEmail;
    @XmlElement(name = "MerchSvcLocCity")
    protected String merchSvcLocCity;
    @XmlElement(name = "MerchSvcLocState")
    protected String merchSvcLocState;
    @XmlElement(name = "MerchSvcLocPostalCode")
    protected String merchSvcLocPostalCode;
    @XmlElement(name = "MerchSvcLocCtry")
    protected String merchSvcLocCtry;
    @XmlElement(name = "MerchSvcLocAddr")
    protected String merchSvcLocAddr;
    @XmlElement(name = "MerchPhNum")
    protected String merchPhNum;
    @XmlElement(name = "MerchAddConInfo")
    protected String merchAddConInfo;
    @XmlElement(name = "MerchPartnerIDCode")
    protected String merchPartnerIDCode;

    /**
     * Gets the value of the merchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchName() {
        return merchName;
    }

    /**
     * Sets the value of the merchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchName(String value) {
        this.merchName = value;
    }

    /**
     * Gets the value of the merchAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchAddr() {
        return merchAddr;
    }

    /**
     * Sets the value of the merchAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchAddr(String value) {
        this.merchAddr = value;
    }

    /**
     * Gets the value of the merchCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCity() {
        return merchCity;
    }

    /**
     * Sets the value of the merchCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCity(String value) {
        this.merchCity = value;
    }

    /**
     * Gets the value of the merchState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchState() {
        return merchState;
    }

    /**
     * Sets the value of the merchState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchState(String value) {
        this.merchState = value;
    }

    /**
     * Gets the value of the merchCnty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCnty() {
        return merchCnty;
    }

    /**
     * Sets the value of the merchCnty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCnty(String value) {
        this.merchCnty = value;
    }

    /**
     * Gets the value of the merchPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchPostalCode() {
        return merchPostalCode;
    }

    /**
     * Sets the value of the merchPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchPostalCode(String value) {
        this.merchPostalCode = value;
    }

    /**
     * Gets the value of the merchCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCtry() {
        return merchCtry;
    }

    /**
     * Sets the value of the merchCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCtry(String value) {
        this.merchCtry = value;
    }

    /**
     * Gets the value of the merchEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchEmail() {
        return merchEmail;
    }

    /**
     * Sets the value of the merchEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchEmail(String value) {
        this.merchEmail = value;
    }

    /**
     * Gets the value of the merchSvcLocCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchSvcLocCity() {
        return merchSvcLocCity;
    }

    /**
     * Sets the value of the merchSvcLocCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchSvcLocCity(String value) {
        this.merchSvcLocCity = value;
    }

    /**
     * Gets the value of the merchSvcLocState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchSvcLocState() {
        return merchSvcLocState;
    }

    /**
     * Sets the value of the merchSvcLocState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchSvcLocState(String value) {
        this.merchSvcLocState = value;
    }

    /**
     * Gets the value of the merchSvcLocPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchSvcLocPostalCode() {
        return merchSvcLocPostalCode;
    }

    /**
     * Sets the value of the merchSvcLocPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchSvcLocPostalCode(String value) {
        this.merchSvcLocPostalCode = value;
    }

    /**
     * Gets the value of the merchSvcLocCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchSvcLocCtry() {
        return merchSvcLocCtry;
    }

    /**
     * Sets the value of the merchSvcLocCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchSvcLocCtry(String value) {
        this.merchSvcLocCtry = value;
    }

    /**
     * Gets the value of the merchSvcLocAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchSvcLocAddr() {
        return merchSvcLocAddr;
    }

    /**
     * Sets the value of the merchSvcLocAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchSvcLocAddr(String value) {
        this.merchSvcLocAddr = value;
    }

    /**
     * Gets the value of the merchPhNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchPhNum() {
        return merchPhNum;
    }

    /**
     * Sets the value of the merchPhNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchPhNum(String value) {
        this.merchPhNum = value;
    }

    /**
     * Gets the value of the merchAddConInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchAddConInfo() {
        return merchAddConInfo;
    }

    /**
     * Sets the value of the merchAddConInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchAddConInfo(String value) {
        this.merchAddConInfo = value;
    }

    /**
     * Gets the value of the merchPartnerIDCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchPartnerIDCode() {
        return merchPartnerIDCode;
    }

    /**
     * Sets the value of the merchPartnerIDCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchPartnerIDCode(String value) {
        this.merchPartnerIDCode = value;
    }

}
