//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppProdPlatCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AppProdPlatCodeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Len2AN">
 *     &lt;enumeration value="BZ"/>
 *     &lt;enumeration value="CN"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="GV"/>
 *     &lt;enumeration value="PO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AppProdPlatCodeType")
@XmlEnum
public enum AppProdPlatCodeType {

    BZ,
    CN,
    CO,
    GV,
    PO;

    public String value() {
        return name();
    }

    public static AppProdPlatCodeType fromValue(String v) {
        return valueOf(v);
    }

}
