//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BackEndGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BackEndGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}IntegratorID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchCustom2" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchCustom3" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchCustom4" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MerchCustom5" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackEndGrp", propOrder = {
    "integratorID",
    "merchCustom2",
    "merchCustom3",
    "merchCustom4",
    "merchCustom5"
})
public class BackEndGrp {

    @XmlElement(name = "IntegratorID")
    protected String integratorID;
    @XmlElement(name = "MerchCustom2")
    protected String merchCustom2;
    @XmlElement(name = "MerchCustom3")
    protected String merchCustom3;
    @XmlElement(name = "MerchCustom4")
    protected String merchCustom4;
    @XmlElement(name = "MerchCustom5")
    protected String merchCustom5;

    /**
     * Gets the value of the integratorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegratorID() {
        return integratorID;
    }

    /**
     * Sets the value of the integratorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegratorID(String value) {
        this.integratorID = value;
    }

    /**
     * Gets the value of the merchCustom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCustom2() {
        return merchCustom2;
    }

    /**
     * Sets the value of the merchCustom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCustom2(String value) {
        this.merchCustom2 = value;
    }

    /**
     * Gets the value of the merchCustom3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCustom3() {
        return merchCustom3;
    }

    /**
     * Sets the value of the merchCustom3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCustom3(String value) {
        this.merchCustom3 = value;
    }

    /**
     * Gets the value of the merchCustom4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCustom4() {
        return merchCustom4;
    }

    /**
     * Sets the value of the merchCustom4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCustom4(String value) {
        this.merchCustom4 = value;
    }

    /**
     * Gets the value of the merchCustom5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCustom5() {
        return merchCustom5;
    }

    /**
     * Sets the value of the merchCustom5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCustom5(String value) {
        this.merchCustom5 = value;
    }

}
