//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusPymtTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BusPymtTypeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max12AN">
 *     &lt;enumeration value="ConsrBillPay"/>
 *     &lt;enumeration value="InstallRepay"/>
 *     &lt;enumeration value="B2BPay"/>
 *     &lt;enumeration value="OLGambling"/>
 *     &lt;enumeration value="WltTrnsfr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BusPymtTypeType")
@XmlEnum
public enum BusPymtTypeType {

    @XmlEnumValue("ConsrBillPay")
    CONSR_BILL_PAY("ConsrBillPay"),
    @XmlEnumValue("InstallRepay")
    INSTALL_REPAY("InstallRepay"),
    @XmlEnumValue("B2BPay")
    B_2_B_PAY("B2BPay"),
    @XmlEnumValue("OLGambling")
    OL_GAMBLING("OLGambling"),
    @XmlEnumValue("WltTrnsfr")
    WLT_TRNSFR("WltTrnsfr");
    private final String value;

    BusPymtTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BusPymtTypeType fromValue(String v) {
        for (BusPymtTypeType c: BusPymtTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
