//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DigComProgTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DigComProgTypeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max10AN">
 *     &lt;enumeration value="NextGenPOI"/>
 *     &lt;enumeration value="PayLinkQR"/>
 *     &lt;enumeration value="XQR"/>
 *     &lt;enumeration value="MultiProg"/>
 *     &lt;enumeration value="InStoreBio"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DigComProgTypeType")
@XmlEnum
public enum DigComProgTypeType {

    @XmlEnumValue("NextGenPOI")
    NEXT_GEN_POI("NextGenPOI"),
    @XmlEnumValue("PayLinkQR")
    PAY_LINK_QR("PayLinkQR"),
    XQR("XQR"),
    @XmlEnumValue("MultiProg")
    MULTI_PROG("MultiProg"),
    @XmlEnumValue("InStoreBio")
    IN_STORE_BIO("InStoreBio");
    private final String value;

    DigComProgTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DigComProgTypeType fromValue(String v) {
        for (DigComProgTypeType c: DigComProgTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
