//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiscAuthIndType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DiscAuthIndType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max9AN">
 *     &lt;enumeration value="ReAuth"/>
 *     &lt;enumeration value="CrdOnFile"/>
 *     &lt;enumeration value="ReSubmit"/>
 *     &lt;enumeration value="TraAgg"/>
 *     &lt;enumeration value="PreAuth"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DiscAuthIndType")
@XmlEnum
public enum DiscAuthIndType {

    @XmlEnumValue("ReAuth")
    RE_AUTH("ReAuth"),
    @XmlEnumValue("CrdOnFile")
    CRD_ON_FILE("CrdOnFile"),
    @XmlEnumValue("ReSubmit")
    RE_SUBMIT("ReSubmit"),
    @XmlEnumValue("TraAgg")
    TRA_AGG("TraAgg"),
    @XmlEnumValue("PreAuth")
    PRE_AUTH("PreAuth");
    private final String value;

    DiscAuthIndType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DiscAuthIndType fromValue(String v) {
        for (DiscAuthIndType c: DiscAuthIndType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
