//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnhdFltPromptNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnhdFltPromptNameType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max4AN">
 *     &lt;enumeration value="BDAY"/>
 *     &lt;enumeration value="BLID"/>
 *     &lt;enumeration value="DLIC"/>
 *     &lt;enumeration value="DLST"/>
 *     &lt;enumeration value="DRID"/>
 *     &lt;enumeration value="HBRD"/>
 *     &lt;enumeration value="HRRD"/>
 *     &lt;enumeration value="INVC"/>
 *     &lt;enumeration value="PONB"/>
 *     &lt;enumeration value="TRHB"/>
 *     &lt;enumeration value="TRIP"/>
 *     &lt;enumeration value="TRLR"/>
 *     &lt;enumeration value="UNIT"/>
 *     &lt;enumeration value="XNID"/>
 *     &lt;enumeration value="AD1"/>
 *     &lt;enumeration value="AD2"/>
 *     &lt;enumeration value="DRI"/>
 *     &lt;enumeration value="EMP"/>
 *     &lt;enumeration value="GEN"/>
 *     &lt;enumeration value="ODM"/>
 *     &lt;enumeration value="TRL"/>
 *     &lt;enumeration value="VHI"/>
 *     &lt;enumeration value="WON"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EnhdFltPromptNameType")
@XmlEnum
public enum EnhdFltPromptNameType {

    BDAY("BDAY"),
    BLID("BLID"),
    DLIC("DLIC"),
    DLST("DLST"),
    DRID("DRID"),
    HBRD("HBRD"),
    HRRD("HRRD"),
    INVC("INVC"),
    PONB("PONB"),
    TRHB("TRHB"),
    TRIP("TRIP"),
    TRLR("TRLR"),
    UNIT("UNIT"),
    XNID("XNID"),
    @XmlEnumValue("AD1")
    AD_1("AD1"),
    @XmlEnumValue("AD2")
    AD_2("AD2"),
    DRI("DRI"),
    EMP("EMP"),
    GEN("GEN"),
    ODM("ODM"),
    TRL("TRL"),
    VHI("VHI"),
    WON("WON");
    private final String value;

    EnhdFltPromptNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnhdFltPromptNameType fromValue(String v) {
        for (EnhdFltPromptNameType c: EnhdFltPromptNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
