//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EVGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EVGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TotTimePlugIn" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TotChrgTime" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}StartTimeOfChrg" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}FinishTimeOfChrg" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ChrgPwrOPCap" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ChrgReasonCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}EstTotDistAdd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}CarbonFootprint" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}EstVehMileAvail" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MaxPowDisp" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ConnectorType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}EVTxnInd" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EVGrp", propOrder = {
    "totTimePlugIn",
    "totChrgTime",
    "startTimeOfChrg",
    "finishTimeOfChrg",
    "chrgPwrOPCap",
    "chrgReasonCode",
    "estTotDistAdd",
    "carbonFootprint",
    "estVehMileAvail",
    "maxPowDisp",
    "connectorType",
    "evTxnInd"
})
public class EVGrp {

    @XmlElement(name = "TotTimePlugIn")
    protected String totTimePlugIn;
    @XmlElement(name = "TotChrgTime")
    protected String totChrgTime;
    @XmlElement(name = "StartTimeOfChrg")
    protected String startTimeOfChrg;
    @XmlElement(name = "FinishTimeOfChrg")
    protected String finishTimeOfChrg;
    @XmlElement(name = "ChrgPwrOPCap")
    protected String chrgPwrOPCap;
    @XmlElement(name = "ChrgReasonCode")
    protected String chrgReasonCode;
    @XmlElement(name = "EstTotDistAdd")
    protected String estTotDistAdd;
    @XmlElement(name = "CarbonFootprint")
    protected String carbonFootprint;
    @XmlElement(name = "EstVehMileAvail")
    protected String estVehMileAvail;
    @XmlElement(name = "MaxPowDisp")
    protected String maxPowDisp;
    @XmlElement(name = "ConnectorType")
    protected String connectorType;
    @XmlElement(name = "EVTxnInd")
    @XmlSchemaType(name = "string")
    protected Max3ANYes evTxnInd;

    /**
     * Gets the value of the totTimePlugIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotTimePlugIn() {
        return totTimePlugIn;
    }

    /**
     * Sets the value of the totTimePlugIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotTimePlugIn(String value) {
        this.totTimePlugIn = value;
    }

    /**
     * Gets the value of the totChrgTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotChrgTime() {
        return totChrgTime;
    }

    /**
     * Sets the value of the totChrgTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotChrgTime(String value) {
        this.totChrgTime = value;
    }

    /**
     * Gets the value of the startTimeOfChrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTimeOfChrg() {
        return startTimeOfChrg;
    }

    /**
     * Sets the value of the startTimeOfChrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTimeOfChrg(String value) {
        this.startTimeOfChrg = value;
    }

    /**
     * Gets the value of the finishTimeOfChrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinishTimeOfChrg() {
        return finishTimeOfChrg;
    }

    /**
     * Sets the value of the finishTimeOfChrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinishTimeOfChrg(String value) {
        this.finishTimeOfChrg = value;
    }

    /**
     * Gets the value of the chrgPwrOPCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChrgPwrOPCap() {
        return chrgPwrOPCap;
    }

    /**
     * Sets the value of the chrgPwrOPCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChrgPwrOPCap(String value) {
        this.chrgPwrOPCap = value;
    }

    /**
     * Gets the value of the chrgReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChrgReasonCode() {
        return chrgReasonCode;
    }

    /**
     * Sets the value of the chrgReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChrgReasonCode(String value) {
        this.chrgReasonCode = value;
    }

    /**
     * Gets the value of the estTotDistAdd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstTotDistAdd() {
        return estTotDistAdd;
    }

    /**
     * Sets the value of the estTotDistAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstTotDistAdd(String value) {
        this.estTotDistAdd = value;
    }

    /**
     * Gets the value of the carbonFootprint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarbonFootprint() {
        return carbonFootprint;
    }

    /**
     * Sets the value of the carbonFootprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarbonFootprint(String value) {
        this.carbonFootprint = value;
    }

    /**
     * Gets the value of the estVehMileAvail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstVehMileAvail() {
        return estVehMileAvail;
    }

    /**
     * Sets the value of the estVehMileAvail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstVehMileAvail(String value) {
        this.estVehMileAvail = value;
    }

    /**
     * Gets the value of the maxPowDisp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxPowDisp() {
        return maxPowDisp;
    }

    /**
     * Sets the value of the maxPowDisp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxPowDisp(String value) {
        this.maxPowDisp = value;
    }

    /**
     * Gets the value of the connectorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectorType() {
        return connectorType;
    }

    /**
     * Sets the value of the connectorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectorType(String value) {
        this.connectorType = value;
    }

    /**
     * Gets the value of the evTxnInd property.
     * 
     * @return
     *     possible object is
     *     {@link Max3ANYes }
     *     
     */
    public Max3ANYes getEVTxnInd() {
        return evTxnInd;
    }

    /**
     * Sets the value of the evTxnInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max3ANYes }
     *     
     */
    public void setEVTxnInd(Max3ANYes value) {
        this.evTxnInd = value;
    }

}
