//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MITPymtTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MITPymtTypeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max12AN">
 *     &lt;enumeration value="Registration"/>
 *     &lt;enumeration value="Subsequent"/>
 *     &lt;enumeration value="Modification"/>
 *     &lt;enumeration value="Cancellation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MITPymtTypeType")
@XmlEnum
public enum MITPymtTypeType {

    @XmlEnumValue("Registration")
    REGISTRATION("Registration"),
    @XmlEnumValue("Subsequent")
    SUBSEQUENT("Subsequent"),
    @XmlEnumValue("Modification")
    MODIFICATION("Modification"),
    @XmlEnumValue("Cancellation")
    CANCELLATION("Cancellation");
    private final String value;

    MITPymtTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MITPymtTypeType fromValue(String v) {
        for (MITPymtTypeType c: MITPymtTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
