//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MnySndGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MnySndGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MTProcessInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PmntTypeId" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}FndSrc" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PartID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}FndRefNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvFirstNm" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvMidInit" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvLastNm" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvStrAddr" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvCity" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvStateCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvCtryCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvPhoneNumber" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendFirstNm" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendMidInit" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendLastNm" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendBusName" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendStrAddr" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendCity" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendStateCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendCtryCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendPhoneNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendDateOfBirth" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendAcctNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}FastRefundInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TranPurpose" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvAcctNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvAcctNumType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendAcctNumType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendIDType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendIDValue" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendIDSubtype" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendIDIssCtry" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvIDType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvIDValue" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvIDSubtype" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvIDIssCtry" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendMidNm" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}RecvMidNm" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PurposeOfPay" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendFullNmRes" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendNatl" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendCtryOfBirth" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendOccup" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SendPersEmailAddr" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MnySndGrp", propOrder = {
    "mtProcessInd",
    "pmntTypeId",
    "fndSrc",
    "partID",
    "fndRefNum",
    "recvFirstNm",
    "recvMidInit",
    "recvLastNm",
    "recvStrAddr",
    "recvCity",
    "recvStateCode",
    "recvCtryCode",
    "recvPostalCode",
    "recvPhoneNumber",
    "sendFirstNm",
    "sendMidInit",
    "sendLastNm",
    "sendBusName",
    "sendStrAddr",
    "sendCity",
    "sendStateCode",
    "sendCtryCode",
    "sendPostalCode",
    "sendPhoneNum",
    "sendDateOfBirth",
    "sendAcctNum",
    "fastRefundInd",
    "tranPurpose",
    "recvAcctNum",
    "recvAcctNumType",
    "sendAcctNumType",
    "sendIDType",
    "sendIDValue",
    "sendIDSubtype",
    "sendIDIssCtry",
    "recvIDType",
    "recvIDValue",
    "recvIDSubtype",
    "recvIDIssCtry",
    "sendMidNm",
    "recvMidNm",
    "purposeOfPay",
    "sendFullNmRes",
    "sendNatl",
    "sendCtryOfBirth",
    "sendOccup",
    "sendPersEmailAddr"
})
public class MnySndGrp {

    @XmlElement(name = "MTProcessInd")
    @XmlSchemaType(name = "string")
    protected MTProcessIndType mtProcessInd;
    @XmlElement(name = "PmntTypeId")
    @XmlSchemaType(name = "string")
    protected PmntTypeIdType pmntTypeId;
    @XmlElement(name = "FndSrc")
    @XmlSchemaType(name = "string")
    protected FndSrcType fndSrc;
    @XmlElement(name = "PartID")
    protected String partID;
    @XmlElement(name = "FndRefNum")
    protected String fndRefNum;
    @XmlElement(name = "RecvFirstNm")
    protected String recvFirstNm;
    @XmlElement(name = "RecvMidInit")
    protected String recvMidInit;
    @XmlElement(name = "RecvLastNm")
    protected String recvLastNm;
    @XmlElement(name = "RecvStrAddr")
    protected String recvStrAddr;
    @XmlElement(name = "RecvCity")
    protected String recvCity;
    @XmlElement(name = "RecvStateCode")
    @XmlSchemaType(name = "string")
    protected MTStateCodeType recvStateCode;
    @XmlElement(name = "RecvCtryCode")
    protected String recvCtryCode;
    @XmlElement(name = "RecvPostalCode")
    protected String recvPostalCode;
    @XmlElement(name = "RecvPhoneNumber")
    protected String recvPhoneNumber;
    @XmlElement(name = "SendFirstNm")
    protected String sendFirstNm;
    @XmlElement(name = "SendMidInit")
    protected String sendMidInit;
    @XmlElement(name = "SendLastNm")
    protected String sendLastNm;
    @XmlElement(name = "SendBusName")
    protected String sendBusName;
    @XmlElement(name = "SendStrAddr")
    protected String sendStrAddr;
    @XmlElement(name = "SendCity")
    protected String sendCity;
    @XmlElement(name = "SendStateCode")
    @XmlSchemaType(name = "string")
    protected MTStateCodeType sendStateCode;
    @XmlElement(name = "SendCtryCode")
    protected String sendCtryCode;
    @XmlElement(name = "SendPostalCode")
    protected String sendPostalCode;
    @XmlElement(name = "SendPhoneNum")
    protected String sendPhoneNum;
    @XmlElement(name = "SendDateOfBirth")
    protected String sendDateOfBirth;
    @XmlElement(name = "SendAcctNum")
    protected String sendAcctNum;
    @XmlElement(name = "FastRefundInd")
    @XmlSchemaType(name = "string")
    protected Max3ANYes fastRefundInd;
    @XmlElement(name = "TranPurpose")
    @XmlSchemaType(name = "string")
    protected TranPurposeType tranPurpose;
    @XmlElement(name = "RecvAcctNum")
    protected String recvAcctNum;
    @XmlElement(name = "RecvAcctNumType")
    @XmlSchemaType(name = "string")
    protected RecvAcctNumTypeType recvAcctNumType;
    @XmlElement(name = "SendAcctNumType")
    @XmlSchemaType(name = "string")
    protected SendAcctNumTypeType sendAcctNumType;
    @XmlElement(name = "SendIDType")
    @XmlSchemaType(name = "string")
    protected SendIDTypeType sendIDType;
    @XmlElement(name = "SendIDValue")
    protected String sendIDValue;
    @XmlElement(name = "SendIDSubtype")
    @XmlSchemaType(name = "string")
    protected SendIDSubtypeType sendIDSubtype;
    @XmlElement(name = "SendIDIssCtry")
    protected String sendIDIssCtry;
    @XmlElement(name = "RecvIDType")
    @XmlSchemaType(name = "string")
    protected RecvIDTypeType recvIDType;
    @XmlElement(name = "RecvIDValue")
    protected String recvIDValue;
    @XmlElement(name = "RecvIDSubtype")
    @XmlSchemaType(name = "string")
    protected RecvIDSubtypeType recvIDSubtype;
    @XmlElement(name = "RecvIDIssCtry")
    protected String recvIDIssCtry;
    @XmlElement(name = "SendMidNm")
    protected String sendMidNm;
    @XmlElement(name = "RecvMidNm")
    protected String recvMidNm;
    @XmlElement(name = "PurposeOfPay")
    protected String purposeOfPay;
    @XmlElement(name = "SendFullNmRes")
    protected String sendFullNmRes;
    @XmlElement(name = "SendNatl")
    protected String sendNatl;
    @XmlElement(name = "SendCtryOfBirth")
    protected String sendCtryOfBirth;
    @XmlElement(name = "SendOccup")
    protected String sendOccup;
    @XmlElement(name = "SendPersEmailAddr")
    protected String sendPersEmailAddr;

    /**
     * Gets the value of the mtProcessInd property.
     * 
     * @return
     *     possible object is
     *     {@link MTProcessIndType }
     *     
     */
    public MTProcessIndType getMTProcessInd() {
        return mtProcessInd;
    }

    /**
     * Sets the value of the mtProcessInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTProcessIndType }
     *     
     */
    public void setMTProcessInd(MTProcessIndType value) {
        this.mtProcessInd = value;
    }

    /**
     * Gets the value of the pmntTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link PmntTypeIdType }
     *     
     */
    public PmntTypeIdType getPmntTypeId() {
        return pmntTypeId;
    }

    /**
     * Sets the value of the pmntTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmntTypeIdType }
     *     
     */
    public void setPmntTypeId(PmntTypeIdType value) {
        this.pmntTypeId = value;
    }

    /**
     * Gets the value of the fndSrc property.
     * 
     * @return
     *     possible object is
     *     {@link FndSrcType }
     *     
     */
    public FndSrcType getFndSrc() {
        return fndSrc;
    }

    /**
     * Sets the value of the fndSrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FndSrcType }
     *     
     */
    public void setFndSrc(FndSrcType value) {
        this.fndSrc = value;
    }

    /**
     * Gets the value of the partID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartID() {
        return partID;
    }

    /**
     * Sets the value of the partID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartID(String value) {
        this.partID = value;
    }

    /**
     * Gets the value of the fndRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFndRefNum() {
        return fndRefNum;
    }

    /**
     * Sets the value of the fndRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFndRefNum(String value) {
        this.fndRefNum = value;
    }

    /**
     * Gets the value of the recvFirstNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvFirstNm() {
        return recvFirstNm;
    }

    /**
     * Sets the value of the recvFirstNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvFirstNm(String value) {
        this.recvFirstNm = value;
    }

    /**
     * Gets the value of the recvMidInit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvMidInit() {
        return recvMidInit;
    }

    /**
     * Sets the value of the recvMidInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvMidInit(String value) {
        this.recvMidInit = value;
    }

    /**
     * Gets the value of the recvLastNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvLastNm() {
        return recvLastNm;
    }

    /**
     * Sets the value of the recvLastNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvLastNm(String value) {
        this.recvLastNm = value;
    }

    /**
     * Gets the value of the recvStrAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvStrAddr() {
        return recvStrAddr;
    }

    /**
     * Sets the value of the recvStrAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvStrAddr(String value) {
        this.recvStrAddr = value;
    }

    /**
     * Gets the value of the recvCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvCity() {
        return recvCity;
    }

    /**
     * Sets the value of the recvCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvCity(String value) {
        this.recvCity = value;
    }

    /**
     * Gets the value of the recvStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link MTStateCodeType }
     *     
     */
    public MTStateCodeType getRecvStateCode() {
        return recvStateCode;
    }

    /**
     * Sets the value of the recvStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTStateCodeType }
     *     
     */
    public void setRecvStateCode(MTStateCodeType value) {
        this.recvStateCode = value;
    }

    /**
     * Gets the value of the recvCtryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvCtryCode() {
        return recvCtryCode;
    }

    /**
     * Sets the value of the recvCtryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvCtryCode(String value) {
        this.recvCtryCode = value;
    }

    /**
     * Gets the value of the recvPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvPostalCode() {
        return recvPostalCode;
    }

    /**
     * Sets the value of the recvPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvPostalCode(String value) {
        this.recvPostalCode = value;
    }

    /**
     * Gets the value of the recvPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvPhoneNumber() {
        return recvPhoneNumber;
    }

    /**
     * Sets the value of the recvPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvPhoneNumber(String value) {
        this.recvPhoneNumber = value;
    }

    /**
     * Gets the value of the sendFirstNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendFirstNm() {
        return sendFirstNm;
    }

    /**
     * Sets the value of the sendFirstNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendFirstNm(String value) {
        this.sendFirstNm = value;
    }

    /**
     * Gets the value of the sendMidInit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendMidInit() {
        return sendMidInit;
    }

    /**
     * Sets the value of the sendMidInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendMidInit(String value) {
        this.sendMidInit = value;
    }

    /**
     * Gets the value of the sendLastNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendLastNm() {
        return sendLastNm;
    }

    /**
     * Sets the value of the sendLastNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendLastNm(String value) {
        this.sendLastNm = value;
    }

    /**
     * Gets the value of the sendBusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendBusName() {
        return sendBusName;
    }

    /**
     * Sets the value of the sendBusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendBusName(String value) {
        this.sendBusName = value;
    }

    /**
     * Gets the value of the sendStrAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendStrAddr() {
        return sendStrAddr;
    }

    /**
     * Sets the value of the sendStrAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendStrAddr(String value) {
        this.sendStrAddr = value;
    }

    /**
     * Gets the value of the sendCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * Sets the value of the sendCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendCity(String value) {
        this.sendCity = value;
    }

    /**
     * Gets the value of the sendStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link MTStateCodeType }
     *     
     */
    public MTStateCodeType getSendStateCode() {
        return sendStateCode;
    }

    /**
     * Sets the value of the sendStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTStateCodeType }
     *     
     */
    public void setSendStateCode(MTStateCodeType value) {
        this.sendStateCode = value;
    }

    /**
     * Gets the value of the sendCtryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendCtryCode() {
        return sendCtryCode;
    }

    /**
     * Sets the value of the sendCtryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendCtryCode(String value) {
        this.sendCtryCode = value;
    }

    /**
     * Gets the value of the sendPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendPostalCode() {
        return sendPostalCode;
    }

    /**
     * Sets the value of the sendPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendPostalCode(String value) {
        this.sendPostalCode = value;
    }

    /**
     * Gets the value of the sendPhoneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendPhoneNum() {
        return sendPhoneNum;
    }

    /**
     * Sets the value of the sendPhoneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendPhoneNum(String value) {
        this.sendPhoneNum = value;
    }

    /**
     * Gets the value of the sendDateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendDateOfBirth() {
        return sendDateOfBirth;
    }

    /**
     * Sets the value of the sendDateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendDateOfBirth(String value) {
        this.sendDateOfBirth = value;
    }

    /**
     * Gets the value of the sendAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendAcctNum() {
        return sendAcctNum;
    }

    /**
     * Sets the value of the sendAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendAcctNum(String value) {
        this.sendAcctNum = value;
    }

    /**
     * Gets the value of the fastRefundInd property.
     * 
     * @return
     *     possible object is
     *     {@link Max3ANYes }
     *     
     */
    public Max3ANYes getFastRefundInd() {
        return fastRefundInd;
    }

    /**
     * Sets the value of the fastRefundInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max3ANYes }
     *     
     */
    public void setFastRefundInd(Max3ANYes value) {
        this.fastRefundInd = value;
    }

    /**
     * Gets the value of the tranPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link TranPurposeType }
     *     
     */
    public TranPurposeType getTranPurpose() {
        return tranPurpose;
    }

    /**
     * Sets the value of the tranPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranPurposeType }
     *     
     */
    public void setTranPurpose(TranPurposeType value) {
        this.tranPurpose = value;
    }

    /**
     * Gets the value of the recvAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvAcctNum() {
        return recvAcctNum;
    }

    /**
     * Sets the value of the recvAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvAcctNum(String value) {
        this.recvAcctNum = value;
    }

    /**
     * Gets the value of the recvAcctNumType property.
     * 
     * @return
     *     possible object is
     *     {@link RecvAcctNumTypeType }
     *     
     */
    public RecvAcctNumTypeType getRecvAcctNumType() {
        return recvAcctNumType;
    }

    /**
     * Sets the value of the recvAcctNumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecvAcctNumTypeType }
     *     
     */
    public void setRecvAcctNumType(RecvAcctNumTypeType value) {
        this.recvAcctNumType = value;
    }

    /**
     * Gets the value of the sendAcctNumType property.
     * 
     * @return
     *     possible object is
     *     {@link SendAcctNumTypeType }
     *     
     */
    public SendAcctNumTypeType getSendAcctNumType() {
        return sendAcctNumType;
    }

    /**
     * Sets the value of the sendAcctNumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendAcctNumTypeType }
     *     
     */
    public void setSendAcctNumType(SendAcctNumTypeType value) {
        this.sendAcctNumType = value;
    }

    /**
     * Gets the value of the sendIDType property.
     * 
     * @return
     *     possible object is
     *     {@link SendIDTypeType }
     *     
     */
    public SendIDTypeType getSendIDType() {
        return sendIDType;
    }

    /**
     * Sets the value of the sendIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendIDTypeType }
     *     
     */
    public void setSendIDType(SendIDTypeType value) {
        this.sendIDType = value;
    }

    /**
     * Gets the value of the sendIDValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendIDValue() {
        return sendIDValue;
    }

    /**
     * Sets the value of the sendIDValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendIDValue(String value) {
        this.sendIDValue = value;
    }

    /**
     * Gets the value of the sendIDSubtype property.
     * 
     * @return
     *     possible object is
     *     {@link SendIDSubtypeType }
     *     
     */
    public SendIDSubtypeType getSendIDSubtype() {
        return sendIDSubtype;
    }

    /**
     * Sets the value of the sendIDSubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendIDSubtypeType }
     *     
     */
    public void setSendIDSubtype(SendIDSubtypeType value) {
        this.sendIDSubtype = value;
    }

    /**
     * Gets the value of the sendIDIssCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendIDIssCtry() {
        return sendIDIssCtry;
    }

    /**
     * Sets the value of the sendIDIssCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendIDIssCtry(String value) {
        this.sendIDIssCtry = value;
    }

    /**
     * Gets the value of the recvIDType property.
     * 
     * @return
     *     possible object is
     *     {@link RecvIDTypeType }
     *     
     */
    public RecvIDTypeType getRecvIDType() {
        return recvIDType;
    }

    /**
     * Sets the value of the recvIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecvIDTypeType }
     *     
     */
    public void setRecvIDType(RecvIDTypeType value) {
        this.recvIDType = value;
    }

    /**
     * Gets the value of the recvIDValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvIDValue() {
        return recvIDValue;
    }

    /**
     * Sets the value of the recvIDValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvIDValue(String value) {
        this.recvIDValue = value;
    }

    /**
     * Gets the value of the recvIDSubtype property.
     * 
     * @return
     *     possible object is
     *     {@link RecvIDSubtypeType }
     *     
     */
    public RecvIDSubtypeType getRecvIDSubtype() {
        return recvIDSubtype;
    }

    /**
     * Sets the value of the recvIDSubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecvIDSubtypeType }
     *     
     */
    public void setRecvIDSubtype(RecvIDSubtypeType value) {
        this.recvIDSubtype = value;
    }

    /**
     * Gets the value of the recvIDIssCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvIDIssCtry() {
        return recvIDIssCtry;
    }

    /**
     * Sets the value of the recvIDIssCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvIDIssCtry(String value) {
        this.recvIDIssCtry = value;
    }

    /**
     * Gets the value of the sendMidNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendMidNm() {
        return sendMidNm;
    }

    /**
     * Sets the value of the sendMidNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendMidNm(String value) {
        this.sendMidNm = value;
    }

    /**
     * Gets the value of the recvMidNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecvMidNm() {
        return recvMidNm;
    }

    /**
     * Sets the value of the recvMidNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecvMidNm(String value) {
        this.recvMidNm = value;
    }

    /**
     * Gets the value of the purposeOfPay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurposeOfPay() {
        return purposeOfPay;
    }

    /**
     * Sets the value of the purposeOfPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurposeOfPay(String value) {
        this.purposeOfPay = value;
    }

    /**
     * Gets the value of the sendFullNmRes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendFullNmRes() {
        return sendFullNmRes;
    }

    /**
     * Sets the value of the sendFullNmRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendFullNmRes(String value) {
        this.sendFullNmRes = value;
    }

    /**
     * Gets the value of the sendNatl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendNatl() {
        return sendNatl;
    }

    /**
     * Sets the value of the sendNatl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendNatl(String value) {
        this.sendNatl = value;
    }

    /**
     * Gets the value of the sendCtryOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendCtryOfBirth() {
        return sendCtryOfBirth;
    }

    /**
     * Sets the value of the sendCtryOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendCtryOfBirth(String value) {
        this.sendCtryOfBirth = value;
    }

    /**
     * Gets the value of the sendOccup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendOccup() {
        return sendOccup;
    }

    /**
     * Sets the value of the sendOccup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendOccup(String value) {
        this.sendOccup = value;
    }

    /**
     * Gets the value of the sendPersEmailAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendPersEmailAddr() {
        return sendPersEmailAddr;
    }

    /**
     * Sets the value of the sendPersEmailAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendPersEmailAddr(String value) {
        this.sendPersEmailAddr = value;
    }

}
