//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NoShowIndType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NoShowIndType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Len6AN">
 *     &lt;enumeration value="NoShow"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NoShowIndType")
@XmlEnum
public enum NoShowIndType {

    @XmlEnumValue("NoShow")
    NO_SHOW("NoShow");
    private final String value;

    NoShowIndType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NoShowIndType fromValue(String v) {
        for (NoShowIndType c: NoShowIndType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
