//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTCGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OTCGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}OTCTranCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}OTCMrktBsktData" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}OTCUniqueId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OTCGrp", propOrder = {
    "otcTranCode",
    "otcMrktBsktData",
    "otcUniqueId"
})
public class OTCGrp {

    @XmlElement(name = "OTCTranCode")
    @XmlSchemaType(name = "string")
    protected OTCTranCodeType otcTranCode;
    @XmlElement(name = "OTCMrktBsktData")
    protected String otcMrktBsktData;
    @XmlElement(name = "OTCUniqueId")
    protected String otcUniqueId;

    /**
     * Gets the value of the otcTranCode property.
     * 
     * @return
     *     possible object is
     *     {@link OTCTranCodeType }
     *     
     */
    public OTCTranCodeType getOTCTranCode() {
        return otcTranCode;
    }

    /**
     * Sets the value of the otcTranCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTCTranCodeType }
     *     
     */
    public void setOTCTranCode(OTCTranCodeType value) {
        this.otcTranCode = value;
    }

    /**
     * Gets the value of the otcMrktBsktData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTCMrktBsktData() {
        return otcMrktBsktData;
    }

    /**
     * Sets the value of the otcMrktBsktData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTCMrktBsktData(String value) {
        this.otcMrktBsktData = value;
    }

    /**
     * Gets the value of the otcUniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTCUniqueId() {
        return otcUniqueId;
    }

    /**
     * Sets the value of the otcUniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTCUniqueId(String value) {
        this.otcUniqueId = value;
    }

}
