//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTCTranCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OTCTranCodeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max18AN">
 *     &lt;enumeration value="BalanceLookup"/>
 *     &lt;enumeration value="ItemQualification"/>
 *     &lt;enumeration value="LimitedSpend"/>
 *     &lt;enumeration value="LimitedSpendRefund"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OTCTranCodeType")
@XmlEnum
public enum OTCTranCodeType {

    @XmlEnumValue("BalanceLookup")
    BALANCE_LOOKUP("BalanceLookup"),
    @XmlEnumValue("ItemQualification")
    ITEM_QUALIFICATION("ItemQualification"),
    @XmlEnumValue("LimitedSpend")
    LIMITED_SPEND("LimitedSpend"),
    @XmlEnumValue("LimitedSpendRefund")
    LIMITED_SPEND_REFUND("LimitedSpendRefund");
    private final String value;

    OTCTranCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OTCTranCodeType fromValue(String v) {
        for (OTCTranCodeType c: OTCTranCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
