//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTRPromptNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OTRPromptNameType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max4AN">
 *     &lt;enumeration value="BDAY"/>
 *     &lt;enumeration value="BLID"/>
 *     &lt;enumeration value="CARR"/>
 *     &lt;enumeration value="CLCD"/>
 *     &lt;enumeration value="CNTN"/>
 *     &lt;enumeration value="CUNB"/>
 *     &lt;enumeration value="CVNM"/>
 *     &lt;enumeration value="DLIC"/>
 *     &lt;enumeration value="DLST"/>
 *     &lt;enumeration value="DMLC"/>
 *     &lt;enumeration value="DRID"/>
 *     &lt;enumeration value="DSCD"/>
 *     &lt;enumeration value="DTKT"/>
 *     &lt;enumeration value="FSTI"/>
 *     &lt;enumeration value="HBRD"/>
 *     &lt;enumeration value="HRRD"/>
 *     &lt;enumeration value="LCCD"/>
 *     &lt;enumeration value="LCST"/>
 *     &lt;enumeration value="LICN"/>
 *     &lt;enumeration value="LSNB"/>
 *     &lt;enumeration value="LSTN"/>
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="ODRD"/>
 *     &lt;enumeration value="PDLN"/>
 *     &lt;enumeration value="PLDS"/>
 *     &lt;enumeration value="PONB"/>
 *     &lt;enumeration value="PPIN"/>
 *     &lt;enumeration value="RTMP"/>
 *     &lt;enumeration value="SLDS"/>
 *     &lt;enumeration value="SPLN"/>
 *     &lt;enumeration value="SSUB"/>
 *     &lt;enumeration value="TRIP"/>
 *     &lt;enumeration value="TRLR"/>
 *     &lt;enumeration value="UNIT"/>
 *     &lt;enumeration value="VEHN"/>
 *     &lt;enumeration value="VHNB"/>
 *     &lt;enumeration value="VHTP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OTRPromptNameType")
@XmlEnum
public enum OTRPromptNameType {

    BDAY,
    BLID,
    CARR,
    CLCD,
    CNTN,
    CUNB,
    CVNM,
    DLIC,
    DLST,
    DMLC,
    DRID,
    DSCD,
    DTKT,
    FSTI,
    HBRD,
    HRRD,
    LCCD,
    LCST,
    LICN,
    LSNB,
    LSTN,
    NAME,
    ODRD,
    PDLN,
    PLDS,
    PONB,
    PPIN,
    RTMP,
    SLDS,
    SPLN,
    SSUB,
    TRIP,
    TRLR,
    UNIT,
    VEHN,
    VHNB,
    VHTP;

    public String value() {
        return name();
    }

    public static OTRPromptNameType fromValue(String v) {
        return valueOf(v);
    }

}
