//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTRProdCatType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OTRProdCatType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max4AN">
 *     &lt;enumeration value="ADD"/>
 *     &lt;enumeration value="ANFR"/>
 *     &lt;enumeration value="BRAK"/>
 *     &lt;enumeration value="CADV"/>
 *     &lt;enumeration value="CLTH"/>
 *     &lt;enumeration value="DEF"/>
 *     &lt;enumeration value="DELI"/>
 *     &lt;enumeration value="ELEC"/>
 *     &lt;enumeration value="ETAX"/>
 *     &lt;enumeration value="EVC1"/>
 *     &lt;enumeration value="EVC2"/>
 *     &lt;enumeration value="EVC3"/>
 *     &lt;enumeration value="FAX"/>
 *     &lt;enumeration value="FLAT"/>
 *     &lt;enumeration value="GROC"/>
 *     &lt;enumeration value="HARD"/>
 *     &lt;enumeration value="IDLE"/>
 *     &lt;enumeration value="LMPR"/>
 *     &lt;enumeration value="LUBE"/>
 *     &lt;enumeration value="MERC"/>
 *     &lt;enumeration value="OIL"/>
 *     &lt;enumeration value="OILC"/>
 *     &lt;enumeration value="PADV"/>
 *     &lt;enumeration value="PART"/>
 *     &lt;enumeration value="PHON"/>
 *     &lt;enumeration value="PNT"/>
 *     &lt;enumeration value="RECP"/>
 *     &lt;enumeration value="REPR"/>
 *     &lt;enumeration value="REST"/>
 *     &lt;enumeration value="SCAN"/>
 *     &lt;enumeration value="SCLE"/>
 *     &lt;enumeration value="SHWR"/>
 *     &lt;enumeration value="TCHN"/>
 *     &lt;enumeration value="TIRE"/>
 *     &lt;enumeration value="TOLL"/>
 *     &lt;enumeration value="TRAL"/>
 *     &lt;enumeration value="TRPP"/>
 *     &lt;enumeration value="UREA"/>
 *     &lt;enumeration value="WASH"/>
 *     &lt;enumeration value="WWFL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OTRProdCatType")
@XmlEnum
public enum OTRProdCatType {

    ADD("ADD"),
    ANFR("ANFR"),
    BRAK("BRAK"),
    CADV("CADV"),
    CLTH("CLTH"),
    DEF("DEF"),
    DELI("DELI"),
    ELEC("ELEC"),
    ETAX("ETAX"),
    @XmlEnumValue("EVC1")
    EVC_1("EVC1"),
    @XmlEnumValue("EVC2")
    EVC_2("EVC2"),
    @XmlEnumValue("EVC3")
    EVC_3("EVC3"),
    FAX("FAX"),
    FLAT("FLAT"),
    GROC("GROC"),
    HARD("HARD"),
    IDLE("IDLE"),
    LMPR("LMPR"),
    LUBE("LUBE"),
    MERC("MERC"),
    OIL("OIL"),
    OILC("OILC"),
    PADV("PADV"),
    PART("PART"),
    PHON("PHON"),
    PNT("PNT"),
    RECP("RECP"),
    REPR("REPR"),
    REST("REST"),
    SCAN("SCAN"),
    SCLE("SCLE"),
    SHWR("SHWR"),
    TCHN("TCHN"),
    TIRE("TIRE"),
    TOLL("TOLL"),
    TRAL("TRAL"),
    TRPP("TRPP"),
    UREA("UREA"),
    WASH("WASH"),
    WWFL("WWFL");
    private final String value;

    OTRProdCatType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OTRProdCatType fromValue(String v) {
        for (OTRProdCatType c: OTRProdCatType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
