//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/fiserv/Merchant/gmfV15.04", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fiserv.rc.gmf.toolkit.proxy;
