//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PFGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PFGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PFInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SellerID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SubMerchID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PFPhoneNumber" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PFAddr" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PFCity" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PFState" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PFPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PFCtry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PFGrp", propOrder = {
    "pfInd",
    "sellerID",
    "subMerchID",
    "pfPhoneNumber",
    "pfAddr",
    "pfCity",
    "pfState",
    "pfPostalCode",
    "pfCtry"
})
public class PFGrp {

    @XmlElement(name = "PFInd")
    @XmlSchemaType(name = "string")
    protected PFIndType pfInd;
    @XmlElement(name = "SellerID")
    protected String sellerID;
    @XmlElement(name = "SubMerchID")
    protected String subMerchID;
    @XmlElement(name = "PFPhoneNumber")
    protected String pfPhoneNumber;
    @XmlElement(name = "PFAddr")
    protected String pfAddr;
    @XmlElement(name = "PFCity")
    protected String pfCity;
    @XmlElement(name = "PFState")
    protected String pfState;
    @XmlElement(name = "PFPostalCode")
    protected String pfPostalCode;
    @XmlElement(name = "PFCtry")
    protected String pfCtry;

    /**
     * Gets the value of the pfInd property.
     * 
     * @return
     *     possible object is
     *     {@link PFIndType }
     *     
     */
    public PFIndType getPFInd() {
        return pfInd;
    }

    /**
     * Sets the value of the pfInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PFIndType }
     *     
     */
    public void setPFInd(PFIndType value) {
        this.pfInd = value;
    }

    /**
     * Gets the value of the sellerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerID() {
        return sellerID;
    }

    /**
     * Sets the value of the sellerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerID(String value) {
        this.sellerID = value;
    }

    /**
     * Gets the value of the subMerchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubMerchID() {
        return subMerchID;
    }

    /**
     * Sets the value of the subMerchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubMerchID(String value) {
        this.subMerchID = value;
    }

    /**
     * Gets the value of the pfPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFPhoneNumber() {
        return pfPhoneNumber;
    }

    /**
     * Sets the value of the pfPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFPhoneNumber(String value) {
        this.pfPhoneNumber = value;
    }

    /**
     * Gets the value of the pfAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFAddr() {
        return pfAddr;
    }

    /**
     * Sets the value of the pfAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFAddr(String value) {
        this.pfAddr = value;
    }

    /**
     * Gets the value of the pfCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFCity() {
        return pfCity;
    }

    /**
     * Sets the value of the pfCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFCity(String value) {
        this.pfCity = value;
    }

    /**
     * Gets the value of the pfState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFState() {
        return pfState;
    }

    /**
     * Sets the value of the pfState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFState(String value) {
        this.pfState = value;
    }

    /**
     * Gets the value of the pfPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFPostalCode() {
        return pfPostalCode;
    }

    /**
     * Sets the value of the pfPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFPostalCode(String value) {
        this.pfPostalCode = value;
    }

    /**
     * Gets the value of the pfCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFCtry() {
        return pfCtry;
    }

    /**
     * Sets the value of the pfCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFCtry(String value) {
        this.pfCtry = value;
    }

}
