//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PINGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PINGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}PINData" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}KeySerialNumData" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}KeyOffset" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}KeyMgtData" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MSKeyID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}NumPINDigits" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}EnhKeyFmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}EnhKeyMgtData" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}EnhKeyChkDig" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}EnhKeySlot" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PINGrp", propOrder = {
    "pinData",
    "keySerialNumData",
    "keyOffset",
    "keyMgtData",
    "msKeyID",
    "numPINDigits",
    "enhKeyFmt",
    "enhKeyMgtData",
    "enhKeyChkDig",
    "enhKeySlot"
})
public class PINGrp {

    @XmlElement(name = "PINData")
    protected String pinData;
    @XmlElement(name = "KeySerialNumData")
    protected String keySerialNumData;
    @XmlElement(name = "KeyOffset")
    protected String keyOffset;
    @XmlElement(name = "KeyMgtData")
    protected String keyMgtData;
    @XmlElement(name = "MSKeyID")
    protected String msKeyID;
    @XmlElement(name = "NumPINDigits")
    protected String numPINDigits;
    @XmlElement(name = "EnhKeyFmt")
    @XmlSchemaType(name = "string")
    protected EnhKeyFmtType enhKeyFmt;
    @XmlElement(name = "EnhKeyMgtData")
    protected String enhKeyMgtData;
    @XmlElement(name = "EnhKeyChkDig")
    protected String enhKeyChkDig;
    @XmlElement(name = "EnhKeySlot")
    protected String enhKeySlot;

    /**
     * Gets the value of the pinData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPINData() {
        return pinData;
    }

    /**
     * Sets the value of the pinData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPINData(String value) {
        this.pinData = value;
    }

    /**
     * Gets the value of the keySerialNumData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeySerialNumData() {
        return keySerialNumData;
    }

    /**
     * Sets the value of the keySerialNumData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeySerialNumData(String value) {
        this.keySerialNumData = value;
    }

    /**
     * Gets the value of the keyOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyOffset() {
        return keyOffset;
    }

    /**
     * Sets the value of the keyOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyOffset(String value) {
        this.keyOffset = value;
    }

    /**
     * Gets the value of the keyMgtData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyMgtData() {
        return keyMgtData;
    }

    /**
     * Sets the value of the keyMgtData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyMgtData(String value) {
        this.keyMgtData = value;
    }

    /**
     * Gets the value of the msKeyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSKeyID() {
        return msKeyID;
    }

    /**
     * Sets the value of the msKeyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSKeyID(String value) {
        this.msKeyID = value;
    }

    /**
     * Gets the value of the numPINDigits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumPINDigits() {
        return numPINDigits;
    }

    /**
     * Sets the value of the numPINDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumPINDigits(String value) {
        this.numPINDigits = value;
    }

    /**
     * Gets the value of the enhKeyFmt property.
     * 
     * @return
     *     possible object is
     *     {@link EnhKeyFmtType }
     *     
     */
    public EnhKeyFmtType getEnhKeyFmt() {
        return enhKeyFmt;
    }

    /**
     * Sets the value of the enhKeyFmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnhKeyFmtType }
     *     
     */
    public void setEnhKeyFmt(EnhKeyFmtType value) {
        this.enhKeyFmt = value;
    }

    /**
     * Gets the value of the enhKeyMgtData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhKeyMgtData() {
        return enhKeyMgtData;
    }

    /**
     * Sets the value of the enhKeyMgtData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhKeyMgtData(String value) {
        this.enhKeyMgtData = value;
    }

    /**
     * Gets the value of the enhKeyChkDig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhKeyChkDig() {
        return enhKeyChkDig;
    }

    /**
     * Sets the value of the enhKeyChkDig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhKeyChkDig(String value) {
        this.enhKeyChkDig = value;
    }

    /**
     * Gets the value of the enhKeySlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhKeySlot() {
        return enhKeySlot;
    }

    /**
     * Sets the value of the enhKeySlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhKeySlot(String value) {
        this.enhKeySlot = value;
    }

}
