//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProdCodeDetGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProdCodeDetGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}NACSProdCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}UnitOfMsure" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}Qnty" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}UnitPrice" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ProdAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}AdjProdAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ProdDiscRatePct" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ProdDiscRateUnit" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ProdDiscRateFlat" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ProdDiscTotAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ProdNetFuelPrice" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProdCodeDetGrp", propOrder = {
    "nacsProdCode",
    "unitOfMsure",
    "qnty",
    "unitPrice",
    "prodAmt",
    "adjProdAmt",
    "prodDiscRatePct",
    "prodDiscRateUnit",
    "prodDiscRateFlat",
    "prodDiscTotAmt",
    "prodNetFuelPrice"
})
public class ProdCodeDetGrp {

    @XmlElement(name = "NACSProdCode")
    protected String nacsProdCode;
    @XmlElement(name = "UnitOfMsure")
    protected String unitOfMsure;
    @XmlElement(name = "Qnty")
    protected String qnty;
    @XmlElement(name = "UnitPrice")
    protected String unitPrice;
    @XmlElement(name = "ProdAmt")
    protected String prodAmt;
    @XmlElement(name = "AdjProdAmt")
    protected String adjProdAmt;
    @XmlElement(name = "ProdDiscRatePct")
    protected String prodDiscRatePct;
    @XmlElement(name = "ProdDiscRateUnit")
    protected String prodDiscRateUnit;
    @XmlElement(name = "ProdDiscRateFlat")
    protected String prodDiscRateFlat;
    @XmlElement(name = "ProdDiscTotAmt")
    protected String prodDiscTotAmt;
    @XmlElement(name = "ProdNetFuelPrice")
    protected String prodNetFuelPrice;

    /**
     * Gets the value of the nacsProdCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNACSProdCode() {
        return nacsProdCode;
    }

    /**
     * Sets the value of the nacsProdCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNACSProdCode(String value) {
        this.nacsProdCode = value;
    }

    /**
     * Gets the value of the unitOfMsure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMsure() {
        return unitOfMsure;
    }

    /**
     * Sets the value of the unitOfMsure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMsure(String value) {
        this.unitOfMsure = value;
    }

    /**
     * Gets the value of the qnty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQnty() {
        return qnty;
    }

    /**
     * Sets the value of the qnty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQnty(String value) {
        this.qnty = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitPrice(String value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the prodAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdAmt() {
        return prodAmt;
    }

    /**
     * Sets the value of the prodAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdAmt(String value) {
        this.prodAmt = value;
    }

    /**
     * Gets the value of the adjProdAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjProdAmt() {
        return adjProdAmt;
    }

    /**
     * Sets the value of the adjProdAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjProdAmt(String value) {
        this.adjProdAmt = value;
    }

    /**
     * Gets the value of the prodDiscRatePct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdDiscRatePct() {
        return prodDiscRatePct;
    }

    /**
     * Sets the value of the prodDiscRatePct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdDiscRatePct(String value) {
        this.prodDiscRatePct = value;
    }

    /**
     * Gets the value of the prodDiscRateUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdDiscRateUnit() {
        return prodDiscRateUnit;
    }

    /**
     * Sets the value of the prodDiscRateUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdDiscRateUnit(String value) {
        this.prodDiscRateUnit = value;
    }

    /**
     * Gets the value of the prodDiscRateFlat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdDiscRateFlat() {
        return prodDiscRateFlat;
    }

    /**
     * Sets the value of the prodDiscRateFlat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdDiscRateFlat(String value) {
        this.prodDiscRateFlat = value;
    }

    /**
     * Gets the value of the prodDiscTotAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdDiscTotAmt() {
        return prodDiscTotAmt;
    }

    /**
     * Sets the value of the prodDiscTotAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdDiscTotAmt(String value) {
        this.prodDiscTotAmt = value;
    }

    /**
     * Gets the value of the prodNetFuelPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdNetFuelPrice() {
        return prodNetFuelPrice;
    }

    /**
     * Sets the value of the prodNetFuelPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdNetFuelPrice(String value) {
        this.prodNetFuelPrice = value;
    }

}
