//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProdCodeGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProdCodeGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ServLvl" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}NumOfProds" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}DiscMethod" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}DiscAgent" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}DiscPlanID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}DiscClientID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}NetFuelPrice" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProdCodeGrp", propOrder = {
    "servLvl",
    "numOfProds",
    "discMethod",
    "discAgent",
    "discPlanID",
    "discClientID",
    "netFuelPrice"
})
public class ProdCodeGrp {

    @XmlElement(name = "ServLvl")
    protected String servLvl;
    @XmlElement(name = "NumOfProds")
    protected String numOfProds;
    @XmlElement(name = "DiscMethod")
    protected String discMethod;
    @XmlElement(name = "DiscAgent")
    @XmlSchemaType(name = "string")
    protected DiscAgentType discAgent;
    @XmlElement(name = "DiscPlanID")
    protected String discPlanID;
    @XmlElement(name = "DiscClientID")
    protected String discClientID;
    @XmlElement(name = "NetFuelPrice")
    protected String netFuelPrice;

    /**
     * Gets the value of the servLvl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServLvl() {
        return servLvl;
    }

    /**
     * Sets the value of the servLvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServLvl(String value) {
        this.servLvl = value;
    }

    /**
     * Gets the value of the numOfProds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumOfProds() {
        return numOfProds;
    }

    /**
     * Sets the value of the numOfProds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumOfProds(String value) {
        this.numOfProds = value;
    }

    /**
     * Gets the value of the discMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscMethod() {
        return discMethod;
    }

    /**
     * Sets the value of the discMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscMethod(String value) {
        this.discMethod = value;
    }

    /**
     * Gets the value of the discAgent property.
     * 
     * @return
     *     possible object is
     *     {@link DiscAgentType }
     *     
     */
    public DiscAgentType getDiscAgent() {
        return discAgent;
    }

    /**
     * Sets the value of the discAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscAgentType }
     *     
     */
    public void setDiscAgent(DiscAgentType value) {
        this.discAgent = value;
    }

    /**
     * Gets the value of the discPlanID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscPlanID() {
        return discPlanID;
    }

    /**
     * Sets the value of the discPlanID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscPlanID(String value) {
        this.discPlanID = value;
    }

    /**
     * Gets the value of the discClientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscClientID() {
        return discClientID;
    }

    /**
     * Sets the value of the discClientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscClientID(String value) {
        this.discClientID = value;
    }

    /**
     * Gets the value of the netFuelPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetFuelPrice() {
        return netFuelPrice;
    }

    /**
     * Sets the value of the netFuelPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetFuelPrice(String value) {
        this.netFuelPrice = value;
    }

}
