//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrstFXEligIndType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrstFXEligIndType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max11AN">
 *     &lt;enumeration value="Eligible"/>
 *     &lt;enumeration value="NotEligible"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrstFXEligIndType")
@XmlEnum
public enum PrstFXEligIndType {

    @XmlEnumValue("Eligible")
    ELIGIBLE("Eligible"),
    @XmlEnumValue("NotEligible")
    NOT_ELIGIBLE("NotEligible");
    private final String value;

    PrstFXEligIndType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrstFXEligIndType fromValue(String v) {
        for (PrstFXEligIndType c: PrstFXEligIndType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
