//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchemeIDType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SchemeIDType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max5AN">
 *     &lt;enumeration value="Visa"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SchemeIDType")
@XmlEnum
public enum SchemeIDType {

    @XmlEnumValue("Visa")
    VISA("Visa"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    SchemeIDType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SchemeIDType fromValue(String v) {
        for (SchemeIDType c: SchemeIDType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
