//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SendAcctNumTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SendAcctNumTypeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Max11AN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="RTNBAN"/>
 *     &lt;enumeration value="IBAN"/>
 *     &lt;enumeration value="CardAcct"/>
 *     &lt;enumeration value="Email"/>
 *     &lt;enumeration value="Phone"/>
 *     &lt;enumeration value="BANBIC"/>
 *     &lt;enumeration value="WalletID"/>
 *     &lt;enumeration value="SocialNetID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SendAcctNumTypeType")
@XmlEnum
public enum SendAcctNumTypeType {

    @XmlEnumValue("Other")
    OTHER("Other"),
    RTNBAN("RTNBAN"),
    IBAN("IBAN"),
    @XmlEnumValue("CardAcct")
    CARD_ACCT("CardAcct"),
    @XmlEnumValue("Email")
    EMAIL("Email"),
    @XmlEnumValue("Phone")
    PHONE("Phone"),
    BANBIC("BANBIC"),
    @XmlEnumValue("WalletID")
    WALLET_ID("WalletID"),
    @XmlEnumValue("SocialNetID")
    SOCIAL_NET_ID("SocialNetID");
    private final String value;

    SendAcctNumTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SendAcctNumTypeType fromValue(String v) {
        for (SendAcctNumTypeType c: SendAcctNumTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
