//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SendIDTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SendIDTypeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV15.04}Len4AN">
 *     &lt;enumeration value="BTHD"/>
 *     &lt;enumeration value="CUID"/>
 *     &lt;enumeration value="NTID"/>
 *     &lt;enumeration value="PASN"/>
 *     &lt;enumeration value="DRLN"/>
 *     &lt;enumeration value="TXIN"/>
 *     &lt;enumeration value="CPNY"/>
 *     &lt;enumeration value="PRXY"/>
 *     &lt;enumeration value="SSNB"/>
 *     &lt;enumeration value="ARNB"/>
 *     &lt;enumeration value="LAWE"/>
 *     &lt;enumeration value="MILI"/>
 *     &lt;enumeration value="TRVL"/>
 *     &lt;enumeration value="EMAL"/>
 *     &lt;enumeration value="PHON"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SendIDTypeType")
@XmlEnum
public enum SendIDTypeType {

    BTHD,
    CUID,
    NTID,
    PASN,
    DRLN,
    TXIN,
    CPNY,
    PRXY,
    SSNB,
    ARNB,
    LAWE,
    MILI,
    TRVL,
    EMAL,
    PHON;

    public String value() {
        return name();
    }

    public static SendIDTypeType fromValue(String v) {
        return valueOf(v);
    }

}
