//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransitGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransitGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TraTranTypeInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TptModeInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ATCUpdInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TraAcsTermInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TraAcsTermFunCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ExPayTranslPAN" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransitGrp", propOrder = {
    "traTranTypeInd",
    "tptModeInd",
    "atcUpdInd",
    "traAcsTermInd",
    "traAcsTermFunCode",
    "exPayTranslPAN"
})
public class TransitGrp {

    @XmlElement(name = "TraTranTypeInd")
    protected String traTranTypeInd;
    @XmlElement(name = "TptModeInd")
    protected String tptModeInd;
    @XmlElement(name = "ATCUpdInd")
    @XmlSchemaType(name = "string")
    protected Max3ANYes atcUpdInd;
    @XmlElement(name = "TraAcsTermInd")
    @XmlSchemaType(name = "string")
    protected Max3ANYes traAcsTermInd;
    @XmlElement(name = "TraAcsTermFunCode")
    protected String traAcsTermFunCode;
    @XmlElement(name = "ExPayTranslPAN")
    protected String exPayTranslPAN;

    /**
     * Gets the value of the traTranTypeInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraTranTypeInd() {
        return traTranTypeInd;
    }

    /**
     * Sets the value of the traTranTypeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraTranTypeInd(String value) {
        this.traTranTypeInd = value;
    }

    /**
     * Gets the value of the tptModeInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTptModeInd() {
        return tptModeInd;
    }

    /**
     * Sets the value of the tptModeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTptModeInd(String value) {
        this.tptModeInd = value;
    }

    /**
     * Gets the value of the atcUpdInd property.
     * 
     * @return
     *     possible object is
     *     {@link Max3ANYes }
     *     
     */
    public Max3ANYes getATCUpdInd() {
        return atcUpdInd;
    }

    /**
     * Sets the value of the atcUpdInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max3ANYes }
     *     
     */
    public void setATCUpdInd(Max3ANYes value) {
        this.atcUpdInd = value;
    }

    /**
     * Gets the value of the traAcsTermInd property.
     * 
     * @return
     *     possible object is
     *     {@link Max3ANYes }
     *     
     */
    public Max3ANYes getTraAcsTermInd() {
        return traAcsTermInd;
    }

    /**
     * Sets the value of the traAcsTermInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max3ANYes }
     *     
     */
    public void setTraAcsTermInd(Max3ANYes value) {
        this.traAcsTermInd = value;
    }

    /**
     * Gets the value of the traAcsTermFunCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraAcsTermFunCode() {
        return traAcsTermFunCode;
    }

    /**
     * Sets the value of the traAcsTermFunCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraAcsTermFunCode(String value) {
        this.traAcsTermFunCode = value;
    }

    /**
     * Gets the value of the exPayTranslPAN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExPayTranslPAN() {
        return exPayTranslPAN;
    }

    /**
     * Sets the value of the exPayTranslPAN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExPayTranslPAN(String value) {
        this.exPayTranslPAN = value;
    }

}
