//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.23 at 11:06:54 AM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisaGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisaGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ACI" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}MrktSpecificDataInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ExistingDebtInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}CardLevelResult" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SourceReasonCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TransID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}VisaBID" maxOccurs="3" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}VisaAUAR" maxOccurs="3" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}TaxAmtCapablt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}SpendQInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}CheckoutInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}QCI" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}VisaAuthInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}StoredCredInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}CofSchedInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}CryptoCrncyPurchInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}ProgDgReasonCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}AcctFundingSrc" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}AppProdPlatCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}AppCHIDMethod" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV15.04}STIPReasonCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisaGrp", propOrder = {
    "aci",
    "mrktSpecificDataInd",
    "existingDebtInd",
    "cardLevelResult",
    "sourceReasonCode",
    "transID",
    "visaBID",
    "visaAUAR",
    "taxAmtCapablt",
    "spendQInd",
    "checkoutInd",
    "qci",
    "visaAuthInd",
    "storedCredInd",
    "cofSchedInd",
    "cryptoCrncyPurchInd",
    "progDgReasonCode",
    "acctFundingSrc",
    "appProdPlatCode",
    "appCHIDMethod",
    "stipReasonCode"
})
public class VisaGrp {

    @XmlElement(name = "ACI")
    protected String aci;
    @XmlElement(name = "MrktSpecificDataInd")
    @XmlSchemaType(name = "string")
    protected MrktSpecificDataIndType mrktSpecificDataInd;
    @XmlElement(name = "ExistingDebtInd")
    protected String existingDebtInd;
    @XmlElement(name = "CardLevelResult")
    protected String cardLevelResult;
    @XmlElement(name = "SourceReasonCode")
    protected String sourceReasonCode;
    @XmlElement(name = "TransID")
    protected String transID;
    @XmlElement(name = "VisaBID")
    protected List<String> visaBID;
    @XmlElement(name = "VisaAUAR")
    protected List<String> visaAUAR;
    @XmlElement(name = "TaxAmtCapablt")
    protected String taxAmtCapablt;
    @XmlElement(name = "SpendQInd")
    protected String spendQInd;
    @XmlElement(name = "CheckoutInd")
    @XmlSchemaType(name = "string")
    protected CheckoutIndType checkoutInd;
    @XmlElement(name = "QCI")
    @XmlSchemaType(name = "string")
    protected QCIType qci;
    @XmlElement(name = "VisaAuthInd")
    @XmlSchemaType(name = "string")
    protected VisaAuthIndType visaAuthInd;
    @XmlElement(name = "StoredCredInd")
    @XmlSchemaType(name = "string")
    protected StoredCredIndType storedCredInd;
    @XmlElement(name = "CofSchedInd")
    @XmlSchemaType(name = "string")
    protected CofSchedIndType cofSchedInd;
    @XmlElement(name = "CryptoCrncyPurchInd")
    @XmlSchemaType(name = "string")
    protected Max3ANYes cryptoCrncyPurchInd;
    @XmlElement(name = "ProgDgReasonCode")
    protected String progDgReasonCode;
    @XmlElement(name = "AcctFundingSrc")
    @XmlSchemaType(name = "string")
    protected AcctFundingSrcType acctFundingSrc;
    @XmlElement(name = "AppProdPlatCode")
    @XmlSchemaType(name = "string")
    protected AppProdPlatCodeType appProdPlatCode;
    @XmlElement(name = "AppCHIDMethod")
    protected String appCHIDMethod;
    @XmlElement(name = "STIPReasonCode")
    protected String stipReasonCode;

    /**
     * Gets the value of the aci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACI() {
        return aci;
    }

    /**
     * Sets the value of the aci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACI(String value) {
        this.aci = value;
    }

    /**
     * Gets the value of the mrktSpecificDataInd property.
     * 
     * @return
     *     possible object is
     *     {@link MrktSpecificDataIndType }
     *     
     */
    public MrktSpecificDataIndType getMrktSpecificDataInd() {
        return mrktSpecificDataInd;
    }

    /**
     * Sets the value of the mrktSpecificDataInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link MrktSpecificDataIndType }
     *     
     */
    public void setMrktSpecificDataInd(MrktSpecificDataIndType value) {
        this.mrktSpecificDataInd = value;
    }

    /**
     * Gets the value of the existingDebtInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistingDebtInd() {
        return existingDebtInd;
    }

    /**
     * Sets the value of the existingDebtInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistingDebtInd(String value) {
        this.existingDebtInd = value;
    }

    /**
     * Gets the value of the cardLevelResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardLevelResult() {
        return cardLevelResult;
    }

    /**
     * Sets the value of the cardLevelResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardLevelResult(String value) {
        this.cardLevelResult = value;
    }

    /**
     * Gets the value of the sourceReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceReasonCode() {
        return sourceReasonCode;
    }

    /**
     * Sets the value of the sourceReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceReasonCode(String value) {
        this.sourceReasonCode = value;
    }

    /**
     * Gets the value of the transID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransID() {
        return transID;
    }

    /**
     * Sets the value of the transID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransID(String value) {
        this.transID = value;
    }

    /**
     * Gets the value of the visaBID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visaBID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisaBID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVisaBID() {
        if (visaBID == null) {
            visaBID = new ArrayList<String>();
        }
        return this.visaBID;
    }

    /**
     * Gets the value of the visaAUAR property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visaAUAR property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisaAUAR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVisaAUAR() {
        if (visaAUAR == null) {
            visaAUAR = new ArrayList<String>();
        }
        return this.visaAUAR;
    }

    /**
     * Gets the value of the taxAmtCapablt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAmtCapablt() {
        return taxAmtCapablt;
    }

    /**
     * Sets the value of the taxAmtCapablt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAmtCapablt(String value) {
        this.taxAmtCapablt = value;
    }

    /**
     * Gets the value of the spendQInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpendQInd() {
        return spendQInd;
    }

    /**
     * Sets the value of the spendQInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpendQInd(String value) {
        this.spendQInd = value;
    }

    /**
     * Gets the value of the checkoutInd property.
     * 
     * @return
     *     possible object is
     *     {@link CheckoutIndType }
     *     
     */
    public CheckoutIndType getCheckoutInd() {
        return checkoutInd;
    }

    /**
     * Sets the value of the checkoutInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckoutIndType }
     *     
     */
    public void setCheckoutInd(CheckoutIndType value) {
        this.checkoutInd = value;
    }

    /**
     * Gets the value of the qci property.
     * 
     * @return
     *     possible object is
     *     {@link QCIType }
     *     
     */
    public QCIType getQCI() {
        return qci;
    }

    /**
     * Sets the value of the qci property.
     * 
     * @param value
     *     allowed object is
     *     {@link QCIType }
     *     
     */
    public void setQCI(QCIType value) {
        this.qci = value;
    }

    /**
     * Gets the value of the visaAuthInd property.
     * 
     * @return
     *     possible object is
     *     {@link VisaAuthIndType }
     *     
     */
    public VisaAuthIndType getVisaAuthInd() {
        return visaAuthInd;
    }

    /**
     * Sets the value of the visaAuthInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisaAuthIndType }
     *     
     */
    public void setVisaAuthInd(VisaAuthIndType value) {
        this.visaAuthInd = value;
    }

    /**
     * Gets the value of the storedCredInd property.
     * 
     * @return
     *     possible object is
     *     {@link StoredCredIndType }
     *     
     */
    public StoredCredIndType getStoredCredInd() {
        return storedCredInd;
    }

    /**
     * Sets the value of the storedCredInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoredCredIndType }
     *     
     */
    public void setStoredCredInd(StoredCredIndType value) {
        this.storedCredInd = value;
    }

    /**
     * Gets the value of the cofSchedInd property.
     * 
     * @return
     *     possible object is
     *     {@link CofSchedIndType }
     *     
     */
    public CofSchedIndType getCofSchedInd() {
        return cofSchedInd;
    }

    /**
     * Sets the value of the cofSchedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link CofSchedIndType }
     *     
     */
    public void setCofSchedInd(CofSchedIndType value) {
        this.cofSchedInd = value;
    }

    /**
     * Gets the value of the cryptoCrncyPurchInd property.
     * 
     * @return
     *     possible object is
     *     {@link Max3ANYes }
     *     
     */
    public Max3ANYes getCryptoCrncyPurchInd() {
        return cryptoCrncyPurchInd;
    }

    /**
     * Sets the value of the cryptoCrncyPurchInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max3ANYes }
     *     
     */
    public void setCryptoCrncyPurchInd(Max3ANYes value) {
        this.cryptoCrncyPurchInd = value;
    }

    /**
     * Gets the value of the progDgReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgDgReasonCode() {
        return progDgReasonCode;
    }

    /**
     * Sets the value of the progDgReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgDgReasonCode(String value) {
        this.progDgReasonCode = value;
    }

    /**
     * Gets the value of the acctFundingSrc property.
     * 
     * @return
     *     possible object is
     *     {@link AcctFundingSrcType }
     *     
     */
    public AcctFundingSrcType getAcctFundingSrc() {
        return acctFundingSrc;
    }

    /**
     * Sets the value of the acctFundingSrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctFundingSrcType }
     *     
     */
    public void setAcctFundingSrc(AcctFundingSrcType value) {
        this.acctFundingSrc = value;
    }

    /**
     * Gets the value of the appProdPlatCode property.
     * 
     * @return
     *     possible object is
     *     {@link AppProdPlatCodeType }
     *     
     */
    public AppProdPlatCodeType getAppProdPlatCode() {
        return appProdPlatCode;
    }

    /**
     * Sets the value of the appProdPlatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppProdPlatCodeType }
     *     
     */
    public void setAppProdPlatCode(AppProdPlatCodeType value) {
        this.appProdPlatCode = value;
    }

    /**
     * Gets the value of the appCHIDMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppCHIDMethod() {
        return appCHIDMethod;
    }

    /**
     * Sets the value of the appCHIDMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppCHIDMethod(String value) {
        this.appCHIDMethod = value;
    }

    /**
     * Gets the value of the stipReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTIPReasonCode() {
        return stipReasonCode;
    }

    /**
     * Sets the value of the stipReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTIPReasonCode(String value) {
        this.stipReasonCode = value;
    }

}
