//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Fiserv.RapidConnect.Datawire.Xml
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://securetransport.dw/rcservice/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://securetransport.dw/rcservice/xml", IsNullable = false)]
    public partial class Request
    {

        private ReqClientIDType reqClientIDField;

        private TransactionType transactionField;

        private string versionField;

        private string clientTimeoutField;

        public Request()
        {
            this.versionField = "3";
        }

        /// <remarks/>
        public ReqClientIDType ReqClientID
        {
            get
            {
                return this.reqClientIDField;
            }
            set
            {
                this.reqClientIDField = value;
            }
        }

        /// <remarks/>
        public TransactionType Transaction
        {
            get
            {
                return this.transactionField;
            }
            set
            {
                this.transactionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string ClientTimeout
        {
            get
            {
                return this.clientTimeoutField;
            }
            set
            {
                this.clientTimeoutField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://securetransport.dw/rcservice/xml")]
    public partial class ReqClientIDType
    {

        private string dIDField;

        private string appField;

        private string authField;

        private string clientRefField;

        /// <remarks/>
        public string DID
        {
            get
            {
                return this.dIDField;
            }
            set
            {
                this.dIDField = value;
            }
        }

        /// <remarks/>
        public string App
        {
            get
            {
                return this.appField;
            }
            set
            {
                this.appField = value;
            }
        }

        /// <remarks/>
        public string Auth
        {
            get
            {
                return this.authField;
            }
            set
            {
                this.authField = value;
            }
        }

        /// <remarks/>
        public string ClientRef
        {
            get
            {
                return this.clientRefField;
            }
            set
            {
                this.clientRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://securetransport.dw/rcservice/xml")]
    public partial class TransactionResponseType
    {

        private string returnCodeField;

        private PayloadType payloadField;

        /// <remarks/>
        public string ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public PayloadType Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://securetransport.dw/rcservice/xml")]
    public partial class PayloadType
    {

        private PayloadTypeEncoding encodingField;

        private bool encodingFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PayloadTypeEncoding Encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EncodingSpecified
        {
            get
            {
                return this.encodingFieldSpecified;
            }
            set
            {
                this.encodingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://securetransport.dw/rcservice/xml")]
    public enum PayloadTypeEncoding
    {

        /// <remarks/>
        xml_escape,

        /// <remarks/>
        cdata,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://securetransport.dw/rcservice/xml")]
    public partial class StatusType
    {

        private string statusCodeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://securetransport.dw/rcservice/xml")]
    public partial class RespClientIDType
    {

        private string dIDField;

        private string clientRefField;

        /// <remarks/>
        public string DID
        {
            get
            {
                return this.dIDField;
            }
            set
            {
                this.dIDField = value;
            }
        }

        /// <remarks/>
        public string ClientRef
        {
            get
            {
                return this.clientRefField;
            }
            set
            {
                this.clientRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://securetransport.dw/rcservice/xml")]
    public partial class TransactionType
    {

        private string serviceIDField;

        private PayloadType payloadField;

        /// <remarks/>
        public string ServiceID
        {
            get
            {
                return this.serviceIDField;
            }
            set
            {
                this.serviceIDField = value;
            }
        }

        /// <remarks/>
        public PayloadType Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://securetransport.dw/rcservice/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://securetransport.dw/rcservice/xml", IsNullable = false)]
    public partial class Response
    {

        private RespClientIDType respClientIDField;

        private StatusType statusField;

        private TransactionResponseType transactionResponseField;

        private string versionField;

        public Response()
        {
            this.versionField = "3";
        }

        /// <remarks/>
        public RespClientIDType RespClientID
        {
            get
            {
                return this.respClientIDField;
            }
            set
            {
                this.respClientIDField = value;
            }
        }

        /// <remarks/>
        public StatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public TransactionResponseType TransactionResponse
        {
            get
            {
                return this.transactionResponseField;
            }
            set
            {
                this.transactionResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
}
